# Keep this list sorted on whatever criteria you prefer because it's displayed in this order.
# Since this is a museum, it's now sorted on year.
gGameDescriptions = [
    # Title, maker, year, directory name (if different from title)
    ('Computer Billiards', 'Sony', 1983, 'ComputerBilliards'),
    ('Frogger', 'Konami', 1983),
    ('Lode Runner', 'Broderbund Software', 1983, 'LodeRunner'),
    ('Mouser', 'Sony', 1983),
    ('Time Pilot', 'Konami', 1983, 'TimePilot'),
    ('Antarctic Adventure', 'Konami', 1984, 'AntarcticAdventure'),
    ('Athletic Land', 'Konami', 1984, 'AthleticLand'),
    ('Chuckie Egg', 'A&F Software', 1984, 'ChuckieEgg'),
    ('Circus Charlie', 'Konami', 1984, 'CircusCharlie'),
    ('Comic Bakery', 'Konami', 1984, 'ComicBakery'),
    ('DoRoDon', 'UPL', 1984),
    ('Ghostbusters', 'Activision', 1984),
    ('H.E.R.O', 'Activision', 1984, 'Hero'),
    ('Hunchback', 'Ocean', 1984),
    ("Konami's Tennis", 'Konami', 1984, 'KonamisTennis'),
    ('Magical Tree', 'Konami', 1984, 'MagicalTree'),
    ('Monkey Academy', 'Konami', 1984, 'MonkeyAcademy'),
    ('Ninja Kage', 'Kawaguchi', 1984, 'NinjaKage'),
    ('Roller Ball', 'HAL', 1984, 'RollerBall'),
    ('Sky Jaguar', 'Konami', 1984, 'SkyJaguar'),
    ('Track & Field 2', 'Konami', 1984, 'TrackAndField2'),
    ('Choplifter!', 'Sony', 1985, 'Choplifter'),
    ('Disc Warrior', 'Alligata', 1985, 'DiscWarrior'),
    ('Eggerland Mystery', 'HAL', 1985, 'EggerlandMystery'),
    ('Hyper Rally', 'Konami', 1985, 'HyperRally'),
    ('Hyper Sports 3', 'Konami', 1985, 'HyperSports3'),
    ('King\'s Valley', 'Konami', 1985, 'KingsValley'),
    ("Konami's Boxing", 'Konami', 1985, 'KonamisBoxing'),
    ("Konami's Ping Pong", 'Konami', 1985, 'KonamisPingPong'),
    ("Konami's Soccer", 'Konami', 1985, 'KonamisSoccer'),
    ("Mopi Ranger", 'Konami', 1985, 'MopiRanger'),
    ('Payload', 'Sony', 1985),
    ('Pippols', 'Konami', 1985),
    ('Raid on Bungeling Bay', 'Sony', 1985, 'RaidOnBungelingBay'),
    ('Rambo', 'Anabasis', 1985),
    ('Road Fighter', 'Konami', 1985, 'RoadFighter'),
    ('Yie Ar Kung-Fu', 'Konami', 1985, 'YieArKungFu'),
    ('Yie Ar Kung-Fu 2', 'Konami', 1985, 'YieArKungFu2'),
    ('Arkanoid', 'Taito', 1986),
    ('Bomber Man Special', 'Hudson Soft', 1986, 'BombermanSpecial'),
    ('Castle Excellent', 'ASCII', 1986, 'CastleExcellent'),
    ('Dunk Shot', 'HAL', 1986, 'DunkShot'),
    ('Eggerland Mystery 2', 'HAL', 1986, 'EggerlandMystery2'),
    ('Flight Deck II', 'Aackosoft', 1986, 'FlightDeck2'),
    ('Green Beret', 'Konami', 1986, 'GreenBeret'),
    ('Gunfright', 'Jaleco', 1986),
    ('Hole in One Professional', 'HAL', 1986, 'HoleInOne'),
    ('De Kinderen van de Wind', 'Infogrames', 1986, 'KinderenVanDeWind'),
    ('Knightmare', 'Konami', 1986),
    ('Knight Tyme', 'MAD Games', 1986, 'KnightTyme'),
    ('Nemesis', 'Konami', 1986),
    ('Penguin Adventure', 'Konami', 1986, 'PenguinAdventure'),
    ('Q-bert', 'Konami', 1986, 'QBert'),
    ('Snake It!', 'Eaglesoft', 1986, 'SnakeIt'),
    ('The Castle', 'HAL', 1986, 'TheCastle'),
    ('The Goonies', 'Konami', 1986, 'Goonies'),
    ('Thexder', 'Game Arts', 1986),
    ('Twin Bee', 'Konami', 1986, 'TwinBee'),
    ('Who Dares Wins 2', 'Alligata', 1986, 'WhoDaresWins2'),
    ('Vampire Killer', 'Konami', 1986, 'VampireKiller'),
    ('Zanac AI', 'Pony', 1986, 'ZanacAI'),
    ('Ancient Ys Vanished Omen', 'Falcom', 1987, 'Ys1'),
    ('Auf Wiedersehen Monty', 'Gremlin', 1987, 'AufWiedersehenMonty'),
    ('Break In', 'Jaleco', 1987, 'BreakIn'),
    ('Bubble Bobble', 'Taito', 1987, 'BubbleBobble'),
    ('Dragon Quest 2', 'Enix', 1987, 'DragonQuest2'),
	('Elite', 'Firebird', 1987),
    ('F-1 spirit', 'Konami', 1987, 'F1Spirit'),
	('Feud', 'Bulldog Software', 1987),
    ('Ganbare Goemon', 'Konami', 1987, 'GanbareGoemon'),
    ('King Kong 2', 'Konami', 1987, 'KingKong2'),
    ('Maze of Galious', 'Konami', 1987, 'MazeOfGalious'),
    ('Metal Gear', 'Konami', 1987, 'MetalGear'),
    ('Nemesis 2', 'Konami', 1987, 'Nemesis2'),
    ('Salamander', 'Konami', 1987),
    ('Shalom', 'Konami', 1987),
    ('Tetris', 'Mirrorsoft', 1987),
    ('Usas', 'Konami', 1987),
    ('Xanadu', 'Falcom', 1987),
    ('Aleste', 'Compile', 1988),
    ('Dragon Slayer IV', 'Falcom', 1988, 'DragonSlayer4'),
    ("King's Valley 2", 'Konami', 1988, 'KingsValley2'),
    ('Nemesis 3', 'Konami', 1988, 'Nemesis3'),
    ('OutRun', 'SEGA', 1988),
    ('Parodius', 'Konami', 1988),
    ('R-Type', 'IREM', 1988),
    ('Contra', 'Konami', 1989),
    ('Space Manbow', 'Konami', 1989, 'SpaceManbow'),
    ('Metal Gear 2: Solid Snake', 'Konami', 1990, 'MetalGear2'),
    ('Quarth', 'Konami', 1990),
	('SD Snatcher', 'Konami', 1990, 'SDSnatcher')
]
